seraphim::SocksSession
ip::tcp::socket seraphim::SocksSession::l_sock_
Referenced by band, handshake_type, traffic.
ip::tcp::socket seraphim::SocksSession::r_sock_
Referenced by band.
uint8_t seraphim::SocksSession::rbuf_[4096][4096]
Referenced by handshake_type, traffic.
shared_ptr<SocksSession> seraphim::SocksSession::self_
Referenced by band, traffic.
seraphim::SocksSession::SocksSession(socket &&sock, endpoint dst_end)
seraphim::SocksSession::SocksSession(socket &&sock, socket &&dst)
virtual seraphim::SocksSession::~SocksSession()
void seraphim::SocksSession::traffic()
References handshake_type, l_sock_, rbuf_, self_.
void seraphim::SocksSession::band(const error_code &ec)
References l_sock_, r_sock_, self_.
Referenced by handshake_type.
void seraphim::SocksSession::handshake_type(const error_code &ec, size_t len)
References band, seraphim::ByteIStream::getN, handshake_host, handshake_ipv4, l_sock_, seraphim::ByteOStream::putN, rbuf_.
Referenced by traffic.
void seraphim::SocksSession::handshake_ipv4(const error_code &ec, size_t len)
Referenced by handshake_type.
void seraphim::SocksSession::handshake_host(const error_code &ec, size_t len)
Referenced by handshake_type.
void seraphim::SocksSession::handshake_resolve(shared_ptr< ip::tcp::resolver > resolver, const error_code &ec, ip::tcp::resolver::iterator itr)
void seraphim::SocksSession::handshake_port(const error_code &ec, size_t len)
void seraphim::SocksSession::handshake_error(const error_code &ec)